/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class WASMWindow!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

OSG_BEGIN_NAMESPACE



//! access the type of the class
inline
OSG::FieldContainerType &WASMWindowBase::getClassType(void)
{
    return _type;
}

//! access the numerical type of the class
inline
OSG::UInt32 WASMWindowBase::getClassTypeId(void)
{
    return _type.getId();
}

inline
OSG::UInt16 WASMWindowBase::getClassGroupId(void)
{
    return _type.getGroupId();
}

/*------------------------------ get -----------------------------------*/

//! Get the value of the WASMWindow::_sfDisplay field.

inline
DisplayP &WASMWindowBase::editDisplay(void)
{
    editSField(DisplayFieldMask);

    return _sfDisplay.getValue();
}

//! Get the value of the WASMWindow::_sfDisplay field.
inline
const DisplayP &WASMWindowBase::getDisplay(void) const
{
    return _sfDisplay.getValue();
}

//! Set the value of the WASMWindow::_sfDisplay field.
inline
void WASMWindowBase::setDisplay(const DisplayP &value)
{
    editSField(DisplayFieldMask);

    _sfDisplay.setValue(value);
}
//! Get the value of the WASMWindow::_sfWindow field.

inline
X11Window &WASMWindowBase::editWindow(void)
{
    editSField(WindowFieldMask);

    return _sfWindow.getValue();
}

//! Get the value of the WASMWindow::_sfWindow field.
inline
const X11Window &WASMWindowBase::getWindow(void) const
{
    return _sfWindow.getValue();
}

//! Set the value of the WASMWindow::_sfWindow field.
inline
void WASMWindowBase::setWindow(const X11Window &value)
{
    editSField(WindowFieldMask);

    _sfWindow.setValue(value);
}
//! Get the value of the WASMWindow::_sfContext field.

inline
GLXContext &WASMWindowBase::editContext(void)
{
    editSField(ContextFieldMask);

    return _sfContext.getValue();
}

//! Get the value of the WASMWindow::_sfContext field.
inline
const GLXContext &WASMWindowBase::getContext(void) const
{
    return _sfContext.getValue();
}

//! Set the value of the WASMWindow::_sfContext field.
inline
void WASMWindowBase::setContext(const GLXContext &value)
{
    editSField(ContextFieldMask);

    _sfContext.setValue(value);
}
//! Get the value of the WASMWindow::_sfFbConfigId field.

inline
Int32 &WASMWindowBase::editFbConfigId(void)
{
    editSField(FbConfigIdFieldMask);

    return _sfFbConfigId.getValue();
}

//! Get the value of the WASMWindow::_sfFbConfigId field.
inline
      Int32  WASMWindowBase::getFbConfigId(void) const
{
    return _sfFbConfigId.getValue();
}

//! Set the value of the WASMWindow::_sfFbConfigId field.
inline
void WASMWindowBase::setFbConfigId(const Int32 value)
{
    editSField(FbConfigIdFieldMask);

    _sfFbConfigId.setValue(value);
}


#ifdef OSG_MT_CPTR_ASPECT
inline
void WASMWindowBase::execSync (      WASMWindowBase *pFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    Inherited::execSync(pFrom, whichField, oOffsets, syncMode, uiSyncInfo);

    if(FieldBits::NoField != (DisplayFieldMask & whichField))
        _sfDisplay.syncWith(pFrom->_sfDisplay);

    if(FieldBits::NoField != (WindowFieldMask & whichField))
        _sfWindow.syncWith(pFrom->_sfWindow);

    if(FieldBits::NoField != (ContextFieldMask & whichField))
        _sfContext.syncWith(pFrom->_sfContext);

    if(FieldBits::NoField != (FbConfigIdFieldMask & whichField))
        _sfFbConfigId.syncWith(pFrom->_sfFbConfigId);
}
#endif


inline
const Char8 *WASMWindowBase::getClassname(void)
{
    return "WASMWindow";
}
OSG_GEN_CONTAINERPTR(WASMWindow);

OSG_END_NAMESPACE

