/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGWASMWINDOWFIELDS_H_
#define _OSGWASMWINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGWindowWASMDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class WASMWindow;

OSG_GEN_CONTAINERPTR(WASMWindow);
/*! \ingroup GrpWindowWASMFieldTraits
    \ingroup GrpLibOSGWindowWASM
 */
template <>
struct FieldTraits<WASMWindow *, nsOSG> :
    public FieldTraitsFCPtrBase<WASMWindow *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<WASMWindow *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_WINDOWWASM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<WASMWindow *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecWASMWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<WASMWindow *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecWASMWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<WASMWindow *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakWASMWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<WASMWindow *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdWASMWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<WASMWindow *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecWASMWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<WASMWindow *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecWASMWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<WASMWindow *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakWASMWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<WASMWindow *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdWASMWindowPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpWindowWASMFieldSFields */
typedef PointerSField<WASMWindow *,
                      RecordedRefCountPolicy, nsOSG  > SFRecWASMWindowPtr;
/*! \ingroup GrpWindowWASMFieldSFields */
typedef PointerSField<WASMWindow *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecWASMWindowPtr;
/*! \ingroup GrpWindowWASMFieldSFields */
typedef PointerSField<WASMWindow *,
                      WeakRefCountPolicy, nsOSG      > SFWeakWASMWindowPtr;
/*! \ingroup GrpWindowWASMFieldSFields */
typedef PointerSField<WASMWindow *,
                      NoRefCountPolicy, nsOSG        > SFUncountedWASMWindowPtr;


/*! \ingroup GrpWindowWASMFieldMFields */
typedef PointerMField<WASMWindow *,
                      RecordedRefCountPolicy, nsOSG  > MFRecWASMWindowPtr;
/*! \ingroup GrpWindowWASMFieldMFields */
typedef PointerMField<WASMWindow *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecWASMWindowPtr;
/*! \ingroup GrpWindowWASMFieldMFields */
typedef PointerMField<WASMWindow *,
                      WeakRefCountPolicy, nsOSG      > MFWeakWASMWindowPtr;
/*! \ingroup GrpWindowWASMFieldMFields */
typedef PointerMField<WASMWindow *,
                      NoRefCountPolicy, nsOSG        > MFUncountedWASMWindowPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpWindowWASMFieldSFields \ingroup GrpLibOSGWindowWASM */
struct SFRecWASMWindowPtr : 
    public PointerSField<WASMWindow *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWASMFieldSFields \ingroup GrpLibOSGWindowWASM */
struct SFUnrecWASMWindowPtr : 
    public PointerSField<WASMWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWASMFieldSFields \ingroup GrpLibOSGWindowWASM */
struct SFWeakWASMWindowPtr :
    public PointerSField<WASMWindow *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpWindowWASMFieldSFields \ingroup GrpLibOSGWindowWASM */
struct SFUncountedWASMWindowPtr :
    public PointerSField<WASMWindow *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpWindowWASMFieldMFields \ingroup GrpLibOSGWindowWASM */
struct MFRecWASMWindowPtr :
    public PointerMField<WASMWindow *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpWindowWASMFieldMFields \ingroup GrpLibOSGWindowWASM */
struct MFUnrecWASMWindowPtr :
    public PointerMField<WASMWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowWASMFieldMFields \ingroup GrpLibOSGWindowWASM */
struct MFWeakWASMWindowPtr :
    public PointerMField<WASMWindow *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpWindowWASMFieldMFields \ingroup GrpLibOSGWindowWASM */
struct MFUncountedWASMWindowPtr :
    public PointerMField<WASMWindow *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGWASMWINDOWFIELDS_H_ */
